import React, {Component} from 'react';
import styled from 'styled-components';
import * as Styled from './styles.js';

class Calendar extends Component {
	render() {
		return (
			<Styled.CalendarContainer>
				<Styled.CalendarRow>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
				</Styled.CalendarRow>
				<Styled.CalendarRow>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
				</Styled.CalendarRow>
				<Styled.CalendarRow>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
				</Styled.CalendarRow>
				<Styled.CalendarRow>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
				</Styled.CalendarRow>
				<Styled.CalendarRow>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
					<Styled.CField></Styled.CField>
				</Styled.CalendarRow>
			</Styled.CalendarContainer>
		);
	}
}

export default Calendar;