import React, {Component} from 'react';
import styled from 'styled-components';
import * as Styled from './styles.js';

class Calendar extends Component {
	render() {
		return (
			<Styled.CalendarContainer>
				<Styled.Row>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
				</Styled.Row>
				<Styled.Row>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
				</Styled.Row>
				<Styled.Row>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
				</Styled.Row>
				<Styled.Row>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
				</Styled.Row>
				<Styled.Row>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
					<Styled.Cell></Styled.Cell>
				</Styled.Row>
			</Styled.CalendarContainer>
		);
	}
}

export default Calendar;